// The Live Link fixture replay (packages/conformance/live-link/, and the
// README there): the scripted session run through the C# StoryletLiveLink
// over a hand-driven fake socket, and every string the client put on the wire
// compared, byte for byte, with the compact form of each frame in frames.json,
// in order. The fixture is generated by the JS client's own test, so a port
// that disagrees is wrong by definition, as with the corpus.
//
// Run by Program.Main beside the corpus families, or alone:
//   dotnet run --project ports/unity/TestHost -- --live-link-connect
// drives the same script through a REAL socket against a listening
// Storyletter (ws://127.0.0.1:4472), for the manual pairing check.

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using StoryletStudio.StoryletEngine;

namespace StoryletStudio.StoryletEngine.TestHost
{
    /// <summary>The test's side of the wire: the harness opens it, and from then
    /// on every frame the link queues is drained straight into Sent. Before it
    /// is opened frames wait in the link's outbox, as they do on a real socket
    /// that is still connecting.</summary>
    internal sealed class FakeLiveLinkSocket : ILiveLinkSocket
    {
        public readonly List<string> Sent = new List<string>();
        private StoryletLiveLink _link;
        private bool _open;

        public void Start(StoryletLiveLink link, string url) { _link = link; }

        /// <summary>The editor answered: hello first, then whatever queued.</summary>
        public void Open()
        {
            _open = true;
            Sent.Add(_link.HelloJson());
            _link.OnSocketOpened();
            Kick();
        }

        public void Kick()
        {
            if (!_open) return;
            while (_link.TryDequeueOutgoing(out var json)) Sent.Add(json);
        }

        public void Close() { _open = false; }
    }

    internal static class LiveLinkFixture
    {
        /// <summary>Replay script.json over the fake socket and hold the sent
        /// frames to frames.json. Returns the failure messages (empty = pass).</summary>
        public static List<string> Run(string repoRoot)
        {
            var failures = new List<string>();
            var dir = Path.Combine(repoRoot, "packages", "conformance", "live-link");
            var script = JObject.Parse(File.ReadAllText(Path.Combine(dir, "script.json")));
            var expected = JArray.Parse(File.ReadAllText(Path.Combine(dir, "frames.json")));
            if (script.Value<string>("schema") != "storylets/live-link-fixture@1")
            {
                failures.Add($"unexpected fixture schema {script.Value<string>("schema")}");
                return failures;
            }

            var bundle = BundleLoader.Parse(File.ReadAllText(Path.Combine(repoRoot, script.Value<string>("bundle"))));
            if (bundle.Content.Hash != script.Value<string>("build"))
            {
                failures.Add($"the bundle's hash {bundle.Content.Hash} is not the build the script claims ({script.Value<string>("build")})");
            }

            var socket = new FakeLiveLinkSocket();
            var link = new StoryletLiveLink(script.Value<string>("build"), script.Value<string>("project"), StoryletLiveLink.DefaultUrl, socket);
            var fixtureEngine = new StoryletStudio.StoryletEngine.Engine(bundle, new EngineOptions { Seed = script.Value<double?>("seed") ?? 0 });
            fixtureEngine.OpenFlow("main");
            RunSteps((JArray)script["steps"], fixtureEngine, link, socket.Open);
            link.Close();

            // The contract is the COMPACT form of each committed frame.
            for (int i = 0; i < Math.Max(expected.Count, socket.Sent.Count); i++)
            {
                if (i >= expected.Count)
                {
                    failures.Add($"frame {i}: the client sent an extra frame: {socket.Sent[i]}");
                    break;
                }
                if (i >= socket.Sent.Count)
                {
                    failures.Add($"frame {i}: the client stopped; expected {Compact(expected[i])}");
                    break;
                }
                var want = Compact(expected[i]);
                if (want != socket.Sent[i])
                {
                    failures.Add($"frame {i}:\n    expected {want}\n    sent     {socket.Sent[i]}");
                    break;
                }
            }
            return failures;
        }

        /// <summary>The live refresh applier (no fixture of its own: it is a save
        /// and a load, both corpus-held): a pushed bundle frame parses, Apply
        /// carries the run across (board, clocks, play log) and refuses another
        /// project's bundle without touching the session.</summary>
        public static List<string> RunApply(string repoRoot)
        {
            var failures = new List<string>();
            var dir = Path.Combine(repoRoot, "packages", "conformance", "live-link");
            var script = JObject.Parse(File.ReadAllText(Path.Combine(dir, "script.json")));
            var json = File.ReadAllText(Path.Combine(repoRoot, script.Value<string>("bundle")));
            var bundle = BundleLoader.Parse(json);
            var engine = new StoryletStudio.StoryletEngine.Engine(bundle, new EngineOptions { Seed = 7 });
            var session = engine.OpenFlow("main");
            session.DealMany();
            session.AdvanceTurns("village", 2);
            var before = StoryletLiveLink.BoardJson(session);

            // The frame as the editor sends it: data is the bundle JSON as a string.
            var push = new JObject { ["t"] = "bundle", ["v"] = 1, ["build"] = "next", ["data"] = json }.ToString(Formatting.None);
            if (!StoryletLiveBundle.TryParsePush(push, out var build, out var data) || build != "next" || data != json)
            {
                failures.Add("TryParsePush did not accept a well-formed bundle frame");
            }
            if (StoryletLiveBundle.TryParsePush("{\"t\":\"hello\"}", out _, out _) || StoryletLiveBundle.TryParsePush("not json", out _, out _))
            {
                failures.Add("TryParsePush accepted a frame that is not a bundle push");
            }

            var r = StoryletLiveBundle.Apply(engine, data);
            if (!r.Ok) failures.Add($"Apply refused the bundle: {r.Error}");
            else if (ReferenceEquals(r.Engine, engine)) failures.Add("Apply returned the old engine");
            else if (r.Engine.GetFlow("main") == null) failures.Add("LoadGame did not rebuild the main flow");
            else if (StoryletLiveLink.BoardJson(r.Engine.GetFlow("main")) != before)
            {
                failures.Add($"the run did not carry across: before {before} after {StoryletLiveLink.BoardJson(r.Engine.GetFlow("main"))}");
            }

            var foreign = (JObject)JObject.Parse(json).DeepClone();
            foreign["content"]["project"] = "someone-else";
            var refused = StoryletLiveBundle.Apply(engine, foreign.ToString(Formatting.None));
            if (refused.Ok) failures.Add("Apply accepted another project's bundle");
            else if (StoryletLiveLink.BoardJson(session) != before) failures.Add("a refused Apply touched the session");
            if (StoryletLiveBundle.Apply(engine, "not json").Ok) failures.Add("Apply accepted a bundle that is not JSON");
            return failures;
        }

        /// <summary>The manual pairing check: the same script over a real socket
        /// to a listening Storyletter, then a pause so the frames land, then
        /// whatever the editor pushed back is reported.</summary>
        public static int Connect(string repoRoot, string url)
        {
            var dir = Path.Combine(repoRoot, "packages", "conformance", "live-link");
            var script = JObject.Parse(File.ReadAllText(Path.Combine(dir, "script.json")));
            var bundle = BundleLoader.Parse(File.ReadAllText(Path.Combine(repoRoot, script.Value<string>("bundle"))));
            var engine = new StoryletStudio.StoryletEngine.Engine(bundle, new EngineOptions { Seed = script.Value<double?>("seed") ?? 0 });
            var session = engine.OpenFlow("main");
            var link = new StoryletLiveLink(bundle.Content.Hash, script.Value<string>("project"), url);
            Console.WriteLine($"connecting to {url} as build {bundle.Content.Hash}");
            RunSteps((JArray)script["steps"], engine, link, () =>
            {
                // "open" is the editor's move on a real socket: wait for it.
                for (int i = 0; i < 100 && link.State == LiveLinkState.Connecting; i++) Thread.Sleep(50);
                Console.WriteLine($"link state: {link.State}");
            });
            Thread.Sleep(1000);
            while (link.TryReceive(out var raw))
            {
                if (StoryletLiveBundle.TryParsePush(raw, out var build, out var data))
                {
                    var r = StoryletLiveBundle.Apply(engine, data);
                    Console.WriteLine(r.Ok ? $"applied pushed bundle {build}" : $"pushed bundle refused: {r.Error}");
                    if (r.Ok)
                    {
                        engine = r.Engine;
                        session = engine.GetFlow("main") ?? engine.OpenFlow("main");
                        link.Attach(engine);
                        link.SetBuild(build);
                    }
                }
            }
            Thread.Sleep(500);
            Console.WriteLine($"link state: {link.State}");
            link.Close();
            return link.State == LiveLinkState.Closed ? 0 : 1;
        }

        private static void RunSteps(JArray steps, Engine engine, StoryletLiveLink link, Action open)
        {
            // `flow` names which participant runs the step; absent means "main",
            // so the single-flow half of the script reads as it always did.
            Flow On(JToken step)
            {
                var id = step.Value<string>("flow") ?? "main";
                return engine.GetFlow(id) ?? throw new Exception($"the script names a closed flow \"{id}\"");
            }
            foreach (var step in steps)
            {
                switch (step.Value<string>("op"))
                {
                    case "attach": link.Attach(engine); break;
                    case "open": open(); break;
                    case "openFlow": engine.OpenFlow(step.Value<string>("flow")); break;
                    case "closeFlow": engine.CloseFlow(step.Value<string>("flow")); break;
                    case "dealMany": On(step).DealMany(StringList(step["hands"])); break;
                    case "deal": On(step).Deal(step.Value<string>("hand")); break;
                    case "play": On(step).Play(step.Value<string>("card"), step.Value<string>("outcome"), step.Value<string>("hand")); break;
                    case "advanceTurns": On(step).AdvanceTurns(step.Value<string>("box"), step.Value<double?>("n") ?? 1); break;
                    case "peek": On(step).Peek(step.Value<string>("box"), StoryletJson.ToStringMap(step["criteria"]), step.Value<int?>("n")); break;
                    default: throw new Exception($"unknown fixture step {step.Value<string>("op")}");
                }
            }
        }

        private static List<string> StringList(JToken token)
        {
            if (token == null) return null;
            var list = new List<string>();
            foreach (var t in (JArray)token) list.Add(t.Value<string>());
            return list;
        }

        /// <summary>JSON.stringify(frame): no whitespace, the file's key order.</summary>
        private static string Compact(JToken frame) => frame.ToString(Formatting.None);
    }
}
